import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import "./globals.css";
import Topbar from "./Components/Topbar";
import Middlebar from "./Components/Middlebar";
import Navbar from "./Components/Navbar";
import Footer from "./Components/Footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
      <Topbar/> 
       <Middlebar/>
       <Navbar/>
       <main >
        {children}
        <Footer />
        </main>
        </body>
        
        
    </html>
  );
}
